
#define AP_PER_SHIELD 4
#define SHIELDS_GREEN 2
#define SHIELDS_YELLOW 1
#define SHIELDS_RED 2
#define SHIELDS_BLUE 1

#define AP_MAX_PICKUP_GREEN ((SHIELDS_GREEN) * AP_PER_SHIELD)
#define AP_MAX_PICKUP_YELLOW ((SHIELDS_YELLOW + SHIELDS_GREEN) * AP_PER_SHIELD)
#define AP_MAX_PICKUP_RED ((SHIELDS_RED + SHIELDS_YELLOW + SHIELDS_GREEN) * AP_PER_SHIELD)
#define AP_MAX_PICKUP_BLUE ((SHIELDS_BLUE + SHIELDS_RED + SHIELDS_YELLOW + SHIELDS_GREEN) * AP_PER_SHIELD)

